# Generated by Django 6.0.6 on 2026-06-17 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day_number', models.PositiveIntegerField(default=1, help_text='Day number in training')),
                ('week_number', models.PositiveIntegerField(default=1, help_text='Week number in training')),
                ('title', models.CharField(help_text="Brief title of today's activities", max_length=200)),
                ('activities', models.TextField(help_text='Detailed description of activities carried out today')),
                ('skills_acquired', models.TextField(blank=True, help_text='Skills, tools, or knowledge gained today')),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced and how you overcame them')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Entry',
                'verbose_name_plural': 'Daily Entries',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EntryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='siwes_logbook.dailyentry')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('entry_submitted', 'Entry Submitted'), ('entry_approved', 'Entry Approved'), ('entry_rejected', 'Entry Rejected'), ('report_submitted', 'Report Submitted'), ('report_approved', 'Report Approved'), ('report_rejected', 'Report Rejected'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('coordinator', 'IT Coordinator')], default='student', max_length=20)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('matric_number', models.CharField(blank=True, help_text='For students only', max_length=30)),
                ('staff_id', models.CharField(blank=True, help_text='For supervisors only', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('training_start_date', models.DateField(blank=True, null=True)),
                ('training_end_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Assigned supervisor (for students)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='siwes_logbook.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('summary', models.TextField(help_text="Overall summary of the week's activities")),
                ('achievements', models.TextField(blank=True, help_text='Key achievements and milestones')),
                ('problems_encountered', models.TextField(blank=True, help_text='Problems encountered during the week')),
                ('plans_for_next_week', models.TextField(blank=True, help_text='Plans and objectives for next week')),
                ('student_signature_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('supervisor_signature_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_weekly_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_number'],
                'unique_together': {('student', 'week_number')},
            },
        ),
    ]
